version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/fbadsfinal

# BeforeInstall:
  #   - location: install_dependencies.sh
  #     timeout: 2300
hooks:
  AfterInstall:
    - location: restart.sh
      timeout: 2300

      
#   ApplicationStart:
#     - location: scripts/start_server.sh
#     - location: scripts/create_test_db.sh
#       timeout: 300
#       runas: root
#   ApplicationStop:
#     - location: scripts/stop_server.sh
#       timeout: 300
#       runas: root
