version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/fbadsfinal
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: restart.sh
      timeout: 2300

# BeforeInstall:
  #   - location: install_dependencies.sh
  #     timeout: 2300
# hooks:
#       runas: root
#   AfterInstall:
#     - location: scripts/change_permissions.sh
#       timeout: 300
#       runas: root
#   ApplicationStart:
#     - location: scripts/start_server.sh
#     - location: scripts/create_test_db.sh
#       timeout: 300
#       runas: root
#   ApplicationStop:
#     - location: scripts/stop_server.sh
#       timeout: 300
#       runas: root
 
