# Generated by Django 3.2.13 on 2022-06-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0002_remove_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
