# Generated by Django 3.2.13 on 2022-06-15 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
