# Generated by Django 3.2.13 on 2022-06-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0009_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
