# Generated by Django 3.2.13 on 2022-07-07 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0013_user_paid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='paid_until',
        ),
        migrations.CreateModel(
            name='Subscription_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=122)),
                ('subscription_id', models.CharField(max_length=122)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
