# Generated by Django 3.2.13 on 2022-07-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0014_auto_20220707_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveads',
            name='ad_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
