# Generated by Django 3.2.13 on 2022-07-08 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0015_saveads_ad_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saveads',
            name='ad_id',
        ),
    ]
