# Generated by Django 3.2.13 on 2022-07-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsapi', '0016_remove_saveads_ad_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_details',
            name='sub_status',
            field=models.BooleanField(default=False),
        ),
    ]
